# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/mkauer/DM_ICE_250/firmware/mdommb_rev1_fw/constrs/clocks.xdc

# XDC: /home/mkauer/DM_ICE_250/firmware/mdommb_rev1_fw/constrs/io.xdc

# IP: ip/lclk_adcclk_wiz/lclk_adcclk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lclk_adcclk_wiz || ORIG_REF_NAME==lclk_adcclk_wiz} -quiet] -quiet
